# Generated by Django 4.0 on 2022-11-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=30)),
                ('res_address', models.CharField(max_length=100)),
                ('res_road_address', models.CharField(max_length=100)),
                ('res_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('res_link', models.URLField(blank=True, null=True)),
                ('res_stars', models.FloatField(blank=True, null=True)),
                ('res_summary', models.CharField(blank=True, max_length=200, null=True)),
                ('res_description', models.TextField(blank=True, null=True)),
                ('res_find', models.CharField(blank=True, max_length=200, null=True)),
                ('res_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('res_comfortables', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
