# Generated by Django 4.0 on 2022-11-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('break_time', models.CharField(blank=True, max_length=20, null=True)),
                ('last_order', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=20)),
                ('sub_category1', models.CharField(max_length=20)),
                ('sub_category2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=40)),
                ('menu_price', models.PositiveIntegerField()),
                ('menu_img', models.ImageField(blank=True, null=True, upload_to='images/menu')),
                ('menu_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=100)),
                ('store_road_address', models.CharField(max_length=100)),
                ('store_tel', models.CharField(blank=True, max_length=30, null=True)),
                ('store_link', models.URLField(blank=True, null=True)),
                ('store_stars', models.FloatField(blank=True, null=True)),
                ('store_summary', models.CharField(blank=True, max_length=200, null=True)),
                ('store_description', models.TextField(blank=True, null=True)),
                ('store_find', models.CharField(blank=True, max_length=200, null=True)),
                ('store_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('store_comfortables', models.CharField(blank=True, max_length=200, null=True)),
                ('store_thumbnail', models.ImageField(blank=True, null=True, upload_to='images/restaurant')),
                ('store_longitude', models.FloatField()),
                ('store_latitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='menu',
            name='menus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.store'),
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.store'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.store'),
        ),
    ]
