# Generated by Django 4.0 on 2022-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_businesshours_category_menu_store_delete_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
