# Generated by Django 4.0 on 2022-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_store_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='break_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='day',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='last_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
