# Generated by Django 4.0 on 2022-11-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_following_user_intro_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/default_profile.jpg', null=True, upload_to='images/users'),
        ),
    ]
