# Generated by Django 4.0 on 2022-11-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_review_restaurant_name_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(blank=True, max_length=450, upload_to='images/reviews'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, max_length=450, upload_to='images/reviews'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, max_length=450, upload_to='images/reviews'),
        ),
    ]
