# Generated by Django 4.0 on 2022-11-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
