# Generated by Django 4.0 on 2022-11-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_review_dt_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
